In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\cheryl\anaconda3\lib\site-packages (1.2.4)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\cheryl\anaconda3\lib\site-packages (from pandas) (2.8.1)
Requirement already satisfied: numpy>=1.16.5 in c:\users\cheryl\anaconda3\lib\site-packages (from pandas) (1.20.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\cheryl\anaconda3\lib\site-packages (from pandas) (2021.1)
Requirement already satisfied: six>=1.5 in c:\users\cheryl\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [2]:
import pandas as pd
df = pd.read_csv("C:/Users/cheryl/OneDrive/Desktop/DSA3101/Frontend/gxs-sentiment-analysis/frontend/dashboard/placeholder_data.csv")
df.head()

,id,date,bank,client,rating,sentiment,intent,service,issue,review
0,1,2024-03-06,GXS,Apple,4,Negative,Praise,C,C1,Great banking app with attractive interest rat...
1,2,2022-11-09,GXS,Apple,5,Negative,Feedback,D,D1,"A bank like no other, no bank have such amazin..."
2,3,2023-09-09,GXS,Apple,1,Negative,Complaint,D,D3,Notice that the drop in interest rate of 0.8% ...
3,4,2023-06-27,GXS,Apple,2,Neutral,Feedback,D,D1,Sending money into my GXS account is a breeze ...
4,5,2022-10-02,GXS,Apple,5,Neutral,Praise,C,C1,I have to say that the UI/UX is one of the bes...

In [3]:
df_2 = df.loc[:, ~df.columns.isin(['id'])]
df_2.head()

,date,bank,client,rating,sentiment,intent,service,issue,review
0,2024-03-06,GXS,Apple,4,Negative,Praise,C,C1,Great banking app with attractive interest rat...
1,2022-11-09,GXS,Apple,5,Negative,Feedback,D,D1,"A bank like no other, no bank have such amazin..."
2,2023-09-09,GXS,Apple,1,Negative,Complaint,D,D3,Notice that the drop in interest rate of 0.8% ...
3,2023-06-27,GXS,Apple,2,Neutral,Feedback,D,D1,Sending money into my GXS account is a breeze ...
4,2022-10-02,GXS,Apple,5,Neutral,Praise,C,C1,I have to say that the UI/UX is one of the bes...

In [15]:
df_2.dtypes

date         object
client       object
bank         object
rating        int64
review       object
service      object
sentiment    object
intent       object
dtype: object

In [10]:
#df_2['date'] = df_2['date'].astype("string")

C:\Users\caleb\AppData\Local\Temp\ipykernel_95356\4252599721.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2['date'] = df_2['date'].astype("string")

In [16]:
df_2.dtypes

date         string[python]
client               object
bank                 object
rating                int64
review               object
service              object
sentiment            object
intent               object
date_only            object
dtype: object

In [4]:
from datetime import datetime

In [20]:
df_2['date'].head()

0     6/3/2024 8:36
1    9/11/2022 3:13
2     9/9/2023 8:33
3    27/6/2023 4:01
4    2/10/2022 4:17
Name: date, dtype: object

In [21]:
df_2['date'] = pd.to_datetime(df_2['date'], format="%d/%m/%Y %H:%M")

df_2['date'] = df_2['date'].dt.date

df_2.head()

C:\Users\caleb\AppData\Local\Temp\ipykernel_95356\2096637456.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2['date'] = pd.to_datetime(df_2['date'], format="%d/%m/%Y %H:%M")
C:\Users\caleb\AppData\Local\Temp\ipykernel_95356\2096637456.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2['date'] = df_2['date'].dt.date

,date,client,bank,rating,review,service,sentiment,intent
0,2024-03-06,Apple,GXS,4,Great banking app with attractive interest rat...,C,Negative,Praise
1,2022-11-09,Apple,GXS,5,"A bank like no other, no bank have such amazin...",D,Negative,Feedback
2,2023-09-09,Apple,GXS,1,Notice that the drop in interest rate of 0.8% ...,D,Negative,Complaint
3,2023-06-27,Apple,GXS,2,Sending money into my GXS account is a breeze ...,D,Neutral,Feedback
4,2022-10-02,Apple,GXS,5,I have to say that the UI/UX is one of the bes...,C,Neutral,Praise

In [28]:
df_3 = df_2.rename(columns={"month_year": "date"})
df_3.head()

,date,client,bank,rating,review,service,sentiment,intent
0,2024-03-06,Apple,GXS,4,Great banking app with attractive interest rat...,C,Negative,Praise
1,2022-11-09,Apple,GXS,5,"A bank like no other, no bank have such amazin...",D,Negative,Feedback
2,2023-09-09,Apple,GXS,1,Notice that the drop in interest rate of 0.8% ...,D,Negative,Complaint
3,2023-06-27,Apple,GXS,2,Sending money into my GXS account is a breeze ...,D,Neutral,Feedback
4,2022-10-02,Apple,GXS,5,I have to say that the UI/UX is one of the bes...,C,Neutral,Praise

In [29]:
df_3["id"] = df_3.index + 1
df_3.head()

,date,client,bank,rating,review,service,sentiment,intent,id
0,2024-03-06,Apple,GXS,4,Great banking app with attractive interest rat...,C,Negative,Praise,1
1,2022-11-09,Apple,GXS,5,"A bank like no other, no bank have such amazin...",D,Negative,Feedback,2
2,2023-09-09,Apple,GXS,1,Notice that the drop in interest rate of 0.8% ...,D,Negative,Complaint,3
3,2023-06-27,Apple,GXS,2,Sending money into my GXS account is a breeze ...,D,Neutral,Feedback,4
4,2022-10-02,Apple,GXS,5,I have to say that the UI/UX is one of the bes...,C,Neutral,Praise,5

In [30]:
import random

In [35]:
fake_values_A = ['A1', 'A2', 'A3']
fake_values_B = ['B1', 'B2', 'B3']
fake_values_C = ['C1', 'C2', 'C3']
fake_values_D = ['D1', 'D2', 'D3']

def assign_value(row):
    if row['service'] == 'A':  # Example condition: if col1 is even
        return random.choice(fake_values_A)
    elif row['service'] == 'B':
        return random.choice(fake_values_B)
    elif row['service'] == 'C':
        return random.choice(fake_values_C)
    else:
        return random.choice(fake_values_D)

In [36]:
df_3['issue'] = df_3.apply(assign_value, axis=1)
df_3.head()

,date,client,bank,rating,review,service,sentiment,intent,id,issue
0,2024-03-06,Apple,GXS,4,Great banking app with attractive interest rat...,C,Negative,Praise,1,C1
1,2022-11-09,Apple,GXS,5,"A bank like no other, no bank have such amazin...",D,Negative,Feedback,2,D1
2,2023-09-09,Apple,GXS,1,Notice that the drop in interest rate of 0.8% ...,D,Negative,Complaint,3,D3
3,2023-06-27,Apple,GXS,2,Sending money into my GXS account is a breeze ...,D,Neutral,Feedback,4,D1
4,2022-10-02,Apple,GXS,5,I have to say that the UI/UX is one of the bes...,C,Neutral,Praise,5,C1

In [37]:
df_4 = df_3[['id', 'date', 'bank', 'client', 'rating', 'sentiment', 'intent', 'service','issue', 'review']]
df_4.head()

,id,date,bank,client,rating,sentiment,intent,service,issue,review
0,1,2024-03-06,GXS,Apple,4,Negative,Praise,C,C1,Great banking app with attractive interest rat...
1,2,2022-11-09,GXS,Apple,5,Negative,Feedback,D,D1,"A bank like no other, no bank have such amazin..."
2,3,2023-09-09,GXS,Apple,1,Negative,Complaint,D,D3,Notice that the drop in interest rate of 0.8% ...
3,4,2023-06-27,GXS,Apple,2,Neutral,Feedback,D,D1,Sending money into my GXS account is a breeze ...
4,5,2022-10-02,GXS,Apple,5,Neutral,Praise,C,C1,I have to say that the UI/UX is one of the bes...

In [43]:
df_4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1094 entries, 0 to 1093
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         1094 non-null   int64
 1   date       1094 non-null   object
 2   bank       1094 non-null   object
 3   client     1094 non-null   object
 4   rating     1094 non-null   int64
 5   sentiment  1094 non-null   object
 6   intent     1094 non-null   object
 7   service    1094 non-null   object
 8   review     1094 non-null   object
dtypes: int64(2), object(7)
memory usage: 77.1+ KB

In [38]:
df_4.to_csv("placeholder_data.csv", index = False)

In [39]:
ph = pd.read_csv("placeholder_data.csv")
ph.head()

,id,date,bank,client,rating,sentiment,intent,service,issue,review
0,1,2024-03-06,GXS,Apple,4,Negative,Praise,C,C1,Great banking app with attractive interest rat...
1,2,2022-11-09,GXS,Apple,5,Negative,Feedback,D,D1,"A bank like no other, no bank have such amazin..."
2,3,2023-09-09,GXS,Apple,1,Negative,Complaint,D,D3,Notice that the drop in interest rate of 0.8% ...
3,4,2023-06-27,GXS,Apple,2,Neutral,Feedback,D,D1,Sending money into my GXS account is a breeze ...
4,5,2022-10-02,GXS,Apple,5,Neutral,Praise,C,C1,I have to say that the UI/UX is one of the bes...